apiVersion: v1
kind: Service
metadata:
  name: bottom-slash
spec:
  clusterIP: None
  selector:
    app: bottom-slash
  ports:
    - port: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bottom-slash
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bottom-slash
  template:
    metadata:
      labels:
        app: bottom-slash
    spec:
      containers:
        - name: bottom-slash
          image: ghcr.io/bottom-software-foundation/bottom-slash:latest
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: bottom-slash
                  key: public-key
          readinessProbe:
            httpGet:
              path: /ping
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bottom-slash
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/acme-challenge-type: dns01
spec:
  tls:
    - secretName: oliver-ni-cert
      hosts:
        - "bottom.oliver.ni"
  rules:
    - host: bottom.oliver.ni
      http:
        paths:
          - backend:
              serviceName: bottom-slash
              servicePort: 4000
